version: "3.9"
services:
  app:
    build: ./app
    expose: ["8000"]
    environment:
    - IDLE_TIMEOUT_SECONDS=900        # 15 minutes
    - ABSOLUTE_TIMEOUT_SECONDS=7200   # 2 hours
    - ROTATE_EVERY_SECONDS=600        # rotate every 10 minutes (example)

  nginx:
    image: nginx:stable
    ports: ["80:80","443:443"]
    volumes:
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./infra/nginx/certs:/etc/nginx/certs:ro
    depends_on: [app]
