version: "3.9"
services:
  app:
    build: ./app
    expose: ["8000"]

  nginx:
    image: nginx:stable
    ports: ["80:80","443:443"]
    volumes:
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./infra/nginx/certs:/etc/nginx/certs:ro
    depends_on: [app]
