services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      ENABLE_HTTPS_REDIRECT: "${ENABLE_HTTPS_REDIRECT:-false}"
      COOKIE_SECURE: "${COOKIE_SECURE:-false}"
      GEO_ENABLE: "${GEO_ENABLE:-false}"
      PORT: "${PORT:-8000}"
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://127.0.0.1:8000/healthz"]
      interval: 10s
      timeout: 3s
      start_period: 20s
      retries: 10
    volumes:
      - ./data:/app/data
      - ./backups:/app/backups
    expose:
      - "8000"

  nginx:
    image: nginx:1.27-alpine
    depends_on:
      app:
        condition: service_healthy
    ports:
      - "8081:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped
