version: "3.9"
services:
  app:
    image: node:18-alpine
    working_dir: /usr/src/app
    environment:
      - NODE_ENV=production
      - PORT=3000
    volumes:
      - ./:/usr/src/app
    command: sh -lc "npm ci --omit=dev && node app.js"
    expose:
      - "3000"
  nginx:
    image: nginx:alpine
    depends_on:
      - app
    ports:
      - "8000:80"
    volumes:
      - ./infra_a3/nginx/nginx.conf_a3_node:/etc/nginx/nginx.conf:ro
    restart: unless-stopped
