name: Security CI (Dependency, Secret & Vulnerability Checks)

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  security-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write

    steps:
      # --- Checkout full repo ---
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # --- Setup Python environment ---
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # --- Install security tools ---
      - name: Install tools
        run: |
          pip install --upgrade pip
          pip install pip-audit bandit pytest

      # --- Dependency audit (pip-audit) ---
      - name: Run pip-audit
        run: |
          pip-audit -r app/requirements.txt --strict

      # --- Static code analysis (Bandit) ---
      - name: Run Bandit (Python security linter)
        run: |
          bandit -r app -ll

      # --- Secret scanning (Gitleaks) ---
      - name: Secret Scan (Gitleaks)
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: false

      # --- Vulnerability scanning (Trivy) ---
      - name: Trivy FS Scan
        uses: aquasecurity/trivy-action@0.24.0
        with:
          scan-type: fs
          ignore-unfixed: true
          format: 'table'
          exit-code: '1'
          vuln-type: 'os,library'
          severity: 'HIGH,CRITICAL'

      # --- Run Pytest (optional sanity check) ---
      - name: Run unit tests
        run: |
          pytest || echo "Tests failed (non-critical during CI scan)"
